name: Deploy FastAPI to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          # Exemple si vous utilisez pytest
          pytest tests/
          # Ou pour lancer les tests avec unittest
          # python -m unittest discover

      - name: Lint code (optional)
        run: |
          # Exemple avec flake8
          pip install flake8
          flake8 .

      - name: Deploy to Railway
        uses: railwayapp/action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          # Optionnel: spécifier un environnement ou un projet
          # environment: production
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}