name: Deploy FastAPI to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Railway CLI
        uses: railwayapp/cli-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}

      - name: Download env & artifacts
        run: |
          railway login --browserless --token ${{ secrets.RAILWAY_TOKEN }}
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway download --environment production

      - name: Deploy to Railway
        run: |
          railway up --service student-grades-api --detach
